apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertservice
  labels:                      
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertservice
  template:
    metadata:
      labels:
        app: alertservice
        release: prometheus    
    spec:
      containers:
        - name: alertcontainer
          image: alertservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: alertservice
  labels:
    app: alertservice
    release: prometheus        
spec:
  type: NodePort  #  Allows access from outside the cluster
  selector:
    app: alertservice
  ports:
    - name: http              
      protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30550  #  Optional: hardcoded for consistency
